version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  dasha-s-dr:
    build: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.dasha-s-dr.rule=Host(`dasha-s-dr.outright.xyz`)"
      - "traefik.http.routers.dasha-s-dr.entrypoints=websecure"
      - "traefik.http.routers.dasha-s-dr.tls=true"
      - "traefik.http.routers.dasha-s-dr.tls.certresolver=leresolver"
    networks:
      - internal
      - web
