version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  dasha-s-dr:
    image: nginx:1.12-alpine
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.ee-client-dashboard.rule=Host(`dasha-s-dr.outright.xyz`)"
      - "traefik.http.routers.ee-client-dashboard.entrypoints=websecure"
      - "traefik.http.routers.ee-client-dashboard.tls=true"
      - "traefik.http.routers.ee-client-dashboard.tls.certresolver=leresolver"
    networks:
      - internal
      - web
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80
